### ISSUE TITLE
Class plagiarism_plugin_copyleaks has a legacy cron method implemented

### ISSUE THREAD

**Issue by aurelienb1** [Copyleaks/moodle-plagiarism_copyleaks#14]
See message below, Plagiarism plugins should implement their own schedule tasks

Execute scheduled task: Background processing of obsolete cron files from plagiarism detection plugins(core\task\plagiarism_cron_task)
... started 13:40:40. Current memory use 13Mo.
Processing cron function for plagiarism_plugin_copyleaks...... started 13:40:40. Current memory use 13Mo.
It has been detected the class plagiarism_plugin_copyleaks has a legacy cron method implemented. Plagiarism plugins should implement their own schedule tasks
.... used 0 dbqueries
... used 0.0097770690917969 seconds
Scheduled task complete: Background processing of obsolete cron files from plagiarism detection plugins (core\task\plagiarism_cron_task)

**Comment by CL-BayanAbuawad** [comment]
Hey @aurelienb1,

As you can see in [here](https://github.com/Copyleaks/moodle-plagiarism_copyleaks/tree/main/classes/task) and [here](https://github.com/Copyleaks/moodle-plagiarism_copyleaks/blob/main/db/tasks.php), we do use scheduled tasks, so I am not sure why you are seeing this message.

Might it be because we have an [empty cron function](https://github.com/Copyleaks/moodle-plagiarism_copyleaks/blob/0c5705e0f0b2f300701538a04d4ea29f72367eaa/lib.php#L393)?

**Comment by aurelienb1** [comment]
Hi,

Yes, i think because you have empty cron function.

I found this in another plagiarism plugin, see MDL-52702 https://tracker.moodle.org/browse/MDL-52702

    /**
     * Workaround MDL-52702 before version 3.1.
     */
    public function cron() {
        // Do nothing.
        // Workaround MDL-52702 before version 3.1.
        // Affected branches moodle 2.7 - 3.0.
    }

Regards
